### ISSUE TITLE
Upgrade causing stack overflow error

### ISSUE THREAD

**Issue by smbryar** [killserver/react-native-screenshot-prevent#14]
I have upgraded from v1.0.7 to v1.0.9 and am now getting these build failures when building using eas. I believe it is an issue with v1.0.8 but I am not sure.

```
/home/expo/workingdir/build/node_modules/react-native-screenshot-prevent/android/src/main/java/com/killserver/screenshotprev/RNScreenshotPreventModule.java:28: error: cannot find symbol
      final Activity activity = this.reactContext.getCurrentActivity();
            ^
  symbol:   class Activity
  location: class RNScreenshotPreventModule
```

```
Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
```

**Comment by killserver** [comment]
thx. upload fix to npm in version 1.0.10. pls - check

**Comment by riorafe** [comment]
Still get an error after upgrading to 1.0.10 @killserver 
![image](https://user-images.githubusercontent.com/46643712/224070125-8c4e8fe2-9853-4aed-8101-2516b17d1209.png)
![image](https://user-images.githubusercontent.com/46643712/224070222-f8bf2840-54c0-4a24-9a1a-fbaa6ab21bcb.png)

**Comment by killserver** [comment]
> Still get an error after upgrading to 1.0.10 @killserver ![image](https://user-images.githubusercontent.com/46643712/224070125-8c4e8fe2-9853-4aed-8101-2516b17d1209.png)
> 
> ![image](https://user-images.githubusercontent.com/46643712/224070695-adb959b7-f967-4b1a-af3b-7a11d939bf62.png)

thx. fix this bug in 1.0.11 version. pls - try

**Comment by riorafe** [comment]
Thankyou @killserver 
Android build has succeded, Im testing on android and IOS. I will update to you soon.
